Player
Kasperice/object-oriented-programming pull request #14
Opened 2020-06-17 15:43 UTC by Pawellos

Nie wiem, czy nie namieszałem za bardzo, bo już się trochę pogubiłem z GITem i nie wiem czy dobrze zrozumiałem te 7 i 8  zadanie :)

2020-06-17 16:55 UTC, Kasperice requested changes

2020-06-17 16:55 UTC, Kasperice commented on shm/.gitignore
> +# Prerequisites
You can delete this file from your branch. It will be merged in another PR

2020-06-17 16:55 UTC, Kasperice commented on shm/cargo.cpp
> +#include "cargo.hpp"
You can delete this file from your branch. It will be merged in another PR

2020-06-17 16:55 UTC, Kasperice commented on shm/cargo.hpp
> +#pragma once
You can delete this file from your branch. It will be merged in another PR

2020-06-17 16:55 UTC, Kasperice commented on shm/ship.cpp
> +#include "ship.hpp"
You can delete this file from your branch. It will be merged in another PR

2020-06-17 16:55 UTC, Kasperice commented on shm/ship.hpp
> +#pragma once
You can delete this file from your branch. It will be merged in another PR

2020-06-17 16:55 UTC, Kasperice commented on shm/player.hpp
> +};
I would format it this way:
```suggestion
class Player{
   private:
    std::unique_ptr<Ship> ship_; 
    size_t availableSpace_;
    size_t money_;
    size_t CountAvailableSpace(Ship ship) const;
    
   public:
    Player(std::unique_ptr<Ship> ship, size_t money, size_t availableSpace); 

    size_t getShip() const;
    size_t getMoney() const; 
    size_t getAvailableSpace() const;
    size_t getSpeed(Ship ship) const;
    
    Cargo* getCargo(Ship ship, size_t index) const;
};
```

2020-06-17 16:55 UTC, Kasperice commented on shm/player.cpp
> +//size_t Player::getShip() const { return ship_; }
Why this is commented?

2020-06-17 16:55 UTC, Kasperice commented on shm/player.cpp
> +    wares += ware.getAmount();
```suggestion
        wares += ware.getAmount();
```

2020-06-17 16:55 UTC, Kasperice commented on shm/player.cpp
> +Cargo* Player::getCargo(Ship ship, size_t index) const{
```suggestion
}

Cargo* Player::getCargo(Ship ship, size_t index) const{
```

2020-06-17 16:55 UTC, Kasperice commented on shm/player.cpp
> +
```suggestion

```

2020-06-17 16:55 UTC, Kasperice commented on shm/player.cpp
> +
```suggestion
```

2020-06-17 16:55 UTC, Kasperice commented on shm/player.cpp
> +    return ware;
How does it work?

2020-06-17 21:01 UTC, Kasperice requested changes

2020-06-17 21:01 UTC, Kasperice commented on shm/player.hpp
> +size_t getAvailableSpace() const;
as @g00fer said on Discord, lets use something else than size_t for values/functions like those (this comment applies to all player files)

2020-06-18 14:21 UTC, Kasperice commented
Can we close this PR? I saw that you created second one

2020-06-18 18:40 UTC, g00fer commented on shm/cargo.cpp
> +Cargo& Cargo::operator+=(size_t amount) {
do not use size_t. See my comments on discord suad-7 channel on that

2020-06-18 18:41 UTC, g00fer requested changes
Do not use size_t (see my comment on squad-7 channel). Make sure it is compiling.

2020-06-19 12:37 UTC, closed without merging